# Configuración de la base de datos (si aplica)
spring.datasource.url=jdbc:postgresql://localhost:5432/GVC-BD
spring.datasource.username=postgres
spring.datasource.password=1234

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Configuración de Thymeleaf (para plantillas HTML)
spring.thymeleaf.enabled=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.mvc.static-path-pattern=/**

# Configuración OAuth2 con Google
spring.security.oauth2.client.registration.google.client-id=1033659696694-frte4nabnvs7ig72r8mio46d6aku42bt.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/google
spring.security.oauth2.client.registration.google.scope=openid, profile, email
spring.security.oauth2.client.registration.google.client-authentication-method=client_secret_basic
spring.security.oauth2.client.registration.google.authorization-grant-type=authorization_code

# Configuración de URIs OAuth2 con Google
spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://openidconnect.googleapis.com/v1/userinfo

spring.security.oauth2.client.provider.google.user-name-attribute=name


# Configuración de Logs para ver detalles
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
